sudo: false
language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip uninstall pytest
  - pip install coveralls
  - pip install -e .[test]
script:
  - py.test --cov=wagtailthemes --cov-report=xml
  - flake8 src/
after_success:
  - coveralls
