sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip uninstall pytest -y
  - pip install coveralls
  - pip install -e .[test]
script:
  - flake8 src/
  - py.test --cov=wagtailthemes --cov-report=xml
after_success:
  - coveralls
